//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Navigation.Designer
{
	/// <summary>
	/// DomainModel NavigationLanguageDomainModel
	/// A designer for creating StateInfo configuration for use within the Navigation
	/// for ASP.NET Web Forms framework.
	/// </summary>
	[DslDesign::DisplayNameResource("Navigation.Designer.NavigationLanguageDomainModel.DisplayName", typeof(global::Navigation.Designer.NavigationLanguageDomainModel), "Navigation.Designer.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Navigation.Designer.NavigationLanguageDomainModel.Description", typeof(global::Navigation.Designer.NavigationLanguageDomainModel), "Navigation.Designer.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("ff6e704d-d5f4-4cba-b3b2-b2793d99fa40")]
	public partial class NavigationLanguageDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// NavigationLanguageDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xff6e704d, 0xd5f4, 0x4cba, 0xb3, 0xb2, 0xb2, 0x79, 0x3d, 0x99, 0xfa, 0x40);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public NavigationLanguageDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(NavigationDiagram),
				typeof(State),
				typeof(NavigationDiagramHasStates),
				typeof(Transition),
				typeof(NavigationLanguageDiagram),
				typeof(TransitionConnector),
				typeof(StateShape),
				typeof(global::Navigation.Designer.FixUpDiagram),
				typeof(global::Navigation.Designer.DecoratorPropertyChanged),
				typeof(global::Navigation.Designer.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(State), "Key", State.KeyDomainPropertyId, typeof(State.KeyPropertyHandler)),
				new DomainMemberInfo(typeof(State), "Page", State.PageDomainPropertyId, typeof(State.PagePropertyHandler)),
				new DomainMemberInfo(typeof(State), "Title", State.TitleDomainPropertyId, typeof(State.TitlePropertyHandler)),
				new DomainMemberInfo(typeof(State), "Route", State.RouteDomainPropertyId, typeof(State.RoutePropertyHandler)),
				new DomainMemberInfo(typeof(State), "TrackCrumbTrail", State.TrackCrumbTrailDomainPropertyId, typeof(State.TrackCrumbTrailPropertyHandler)),
				new DomainMemberInfo(typeof(State), "CheckPhysicalUrlAccess", State.CheckPhysicalUrlAccessDomainPropertyId, typeof(State.CheckPhysicalUrlAccessPropertyHandler)),
				new DomainMemberInfo(typeof(State), "Masters", State.MastersDomainPropertyId, typeof(State.MastersPropertyHandler)),
				new DomainMemberInfo(typeof(State), "Theme", State.ThemeDomainPropertyId, typeof(State.ThemePropertyHandler)),
				new DomainMemberInfo(typeof(State), "ResourceType", State.ResourceTypeDomainPropertyId, typeof(State.ResourceTypePropertyHandler)),
				new DomainMemberInfo(typeof(State), "ResourceKey", State.ResourceKeyDomainPropertyId, typeof(State.ResourceKeyPropertyHandler)),
				new DomainMemberInfo(typeof(State), "Order", State.OrderDomainPropertyId, typeof(State.OrderPropertyHandler)),
				new DomainMemberInfo(typeof(State), "Initial", State.InitialDomainPropertyId, typeof(State.InitialPropertyHandler)),
				new DomainMemberInfo(typeof(State), "Path", State.PathDomainPropertyId, typeof(State.PathPropertyHandler)),
				new DomainMemberInfo(typeof(State), "DialogKey", State.DialogKeyDomainPropertyId, typeof(State.DialogKeyPropertyHandler)),
				new DomainMemberInfo(typeof(State), "DialogTitle", State.DialogTitleDomainPropertyId, typeof(State.DialogTitlePropertyHandler)),
				new DomainMemberInfo(typeof(State), "DialogResourceType", State.DialogResourceTypeDomainPropertyId, typeof(State.DialogResourceTypePropertyHandler)),
				new DomainMemberInfo(typeof(State), "DialogResourceKey", State.DialogResourceKeyDomainPropertyId, typeof(State.DialogResourceKeyPropertyHandler)),
				new DomainMemberInfo(typeof(State), "DialogOrder", State.DialogOrderDomainPropertyId, typeof(State.DialogOrderPropertyHandler)),
				new DomainMemberInfo(typeof(State), "MobilePage", State.MobilePageDomainPropertyId, typeof(State.MobilePagePropertyHandler)),
				new DomainMemberInfo(typeof(State), "MobileRoute", State.MobileRouteDomainPropertyId, typeof(State.MobileRoutePropertyHandler)),
				new DomainMemberInfo(typeof(State), "MobileTheme", State.MobileThemeDomainPropertyId, typeof(State.MobileThemePropertyHandler)),
				new DomainMemberInfo(typeof(State), "MobileMasters", State.MobileMastersDomainPropertyId, typeof(State.MobileMastersPropertyHandler)),
				new DomainMemberInfo(typeof(State), "Defaults", State.DefaultsDomainPropertyId, typeof(State.DefaultsPropertyHandler)),
				new DomainMemberInfo(typeof(Transition), "Key", Transition.KeyDomainPropertyId, typeof(Transition.KeyPropertyHandler)),
				new DomainMemberInfo(typeof(Transition), "CanNavigateBack", Transition.CanNavigateBackDomainPropertyId, typeof(Transition.CanNavigateBackPropertyHandler)),
				new DomainMemberInfo(typeof(Transition), "Order", Transition.OrderDomainPropertyId, typeof(Transition.OrderPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(NavigationDiagramHasStates), "NavigationDiagram", NavigationDiagramHasStates.NavigationDiagramDomainRoleId),
				new DomainRolePlayerInfo(typeof(NavigationDiagramHasStates), "Element", NavigationDiagramHasStates.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(Transition), "Predecessor", Transition.PredecessorDomainRoleId),
				new DomainRolePlayerInfo(typeof(Transition), "Successor", Transition.SuccessorDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(5);
				createElementMap.Add(typeof(NavigationDiagram), 0);
				createElementMap.Add(typeof(State), 1);
				createElementMap.Add(typeof(NavigationLanguageDiagram), 2);
				createElementMap.Add(typeof(TransitionConnector), 3);
				createElementMap.Add(typeof(StateShape), 4);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Navigation.Designer.NavigationLanguageDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new NavigationDiagram(partition, propertyAssignments);
				case 1: return new State(partition, propertyAssignments);
				case 2: return new NavigationLanguageDiagram(partition, propertyAssignments);
				case 3: return new TransitionConnector(partition, propertyAssignments);
				case 4: return new StateShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(2);
				createElementLinkMap.Add(typeof(NavigationDiagramHasStates), 0);
				createElementLinkMap.Add(typeof(Transition), 1);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Navigation.Designer.NavigationLanguageDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new NavigationDiagramHasStates(partition, roleAssignments, propertyAssignments);
				case 1: return new Transition(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Navigation.Designer.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return NavigationLanguageDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (NavigationLanguageDomainModel.resourceManager == null)
				{
					NavigationLanguageDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(NavigationLanguageDomainModel).Assembly);
				}
				return NavigationLanguageDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return NavigationLanguageDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return NavigationLanguageDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (NavigationLanguageDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new NavigationLanguageCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					NavigationLanguageDomainModel.copyClosure = copyFilter;
				}
				return NavigationLanguageDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (NavigationLanguageDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new NavigationLanguageDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					NavigationLanguageDomainModel.removeClosure = removeFilter;
				}
				return NavigationLanguageDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Navigation.Designer.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::Navigation.Designer.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::Navigation.Designer.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Navigation.Designer.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::Navigation.Designer.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::Navigation.Designer.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class NavigationLanguageDeleteClosure : NavigationLanguageDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public NavigationLanguageDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class NavigationLanguageDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public NavigationLanguageDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Navigation.Designer.NavigationDiagramHasStates.ElementDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class NavigationLanguageCopyClosure : NavigationLanguageCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public NavigationLanguageCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class NavigationLanguageCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public NavigationLanguageCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

