//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigation.Designer
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "nav";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Navigation Diagram";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Navigation";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID NavigationLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NavigationLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID NavigationLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NavigationLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewNavigationLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NavigationLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string NavigationLanguagePackageId = "c37cb6a6-6192-4282-a9c6-37f88ffdf037";
		
		// Editor factory identifier
		public const string NavigationLanguageEditorFactoryId = "f958d75c-6cc6-41c1-9601-eb0682633ea7";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string NavigationLanguageModelExplorerToolWindowId = "2203b6fe-74d7-45c1-ab06-39db0f96d206";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Navigation.Designer
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string NavigationLanguageCommandSetId = "062d0303-edd7-48e5-bf42-3b5a47daa845";
	}
}