
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateComponentDescriptorH.js
 */

#pragma once

#include <react/renderer/components/navigationreactnative/ShadowNodes.h>
#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <NVActionBarShadowNode.h>
#include <NVBarButtonShadowNode.h>
#include <NVSearchBarShadowNode.h>
#include <NVTabBarItemShadowNode.h>
#include <NVTitleBarShadowNode.h>

namespace facebook {
namespace react {

using NVActionBarComponentDescriptor = ConcreteComponentDescriptor<NVActionBarShadowNode>;
using NVBarButtonComponentDescriptor = ConcreteComponentDescriptor<NVBarButtonShadowNode>;
using NVBottomAppBarComponentDescriptor = ConcreteComponentDescriptor<NVBottomAppBarShadowNode>;
using NVBottomSheetComponentDescriptor = ConcreteComponentDescriptor<NVBottomSheetShadowNode>;
using NVCollapsingBarComponentDescriptor = ConcreteComponentDescriptor<NVCollapsingBarShadowNode>;
using NVCoordinatorLayoutComponentDescriptor = ConcreteComponentDescriptor<NVCoordinatorLayoutShadowNode>;
using NVExtendedFloatingActionButtonComponentDescriptor = ConcreteComponentDescriptor<NVExtendedFloatingActionButtonShadowNode>;
using NVFloatingActionButtonComponentDescriptor = ConcreteComponentDescriptor<NVFloatingActionButtonShadowNode>;
using NVLeftBarComponentDescriptor = ConcreteComponentDescriptor<NVLeftBarShadowNode>;
using NVNavigationBarComponentDescriptor = ConcreteComponentDescriptor<NVNavigationBarShadowNode>;
using NVNavigationStackComponentDescriptor = ConcreteComponentDescriptor<NVNavigationStackShadowNode>;
using NVRightBarComponentDescriptor = ConcreteComponentDescriptor<NVRightBarShadowNode>;
using NVSceneComponentDescriptor = ConcreteComponentDescriptor<NVSceneShadowNode>;
using NVSearchBarComponentDescriptor = ConcreteComponentDescriptor<NVSearchBarShadowNode>;
using NVSegmentedTabComponentDescriptor = ConcreteComponentDescriptor<NVSegmentedTabShadowNode>;
using NVSharedElementComponentDescriptor = ConcreteComponentDescriptor<NVSharedElementShadowNode>;
using NVStatusBarComponentDescriptor = ConcreteComponentDescriptor<NVStatusBarShadowNode>;
using NVTabBarItemComponentDescriptor = ConcreteComponentDescriptor<NVTabBarItemShadowNode>;
using NVTabBarComponentDescriptor = ConcreteComponentDescriptor<NVTabBarShadowNode>;
using NVTabBarPagerComponentDescriptor = ConcreteComponentDescriptor<NVTabBarPagerShadowNode>;
using NVTabBarPagerRTLComponentDescriptor = ConcreteComponentDescriptor<NVTabBarPagerRTLShadowNode>;
using NVTabLayoutComponentDescriptor = ConcreteComponentDescriptor<NVTabLayoutShadowNode>;
using NVTabLayoutRTLComponentDescriptor = ConcreteComponentDescriptor<NVTabLayoutRTLShadowNode>;
using NVTabNavigationComponentDescriptor = ConcreteComponentDescriptor<NVTabNavigationShadowNode>;
using NVTitleBarComponentDescriptor = ConcreteComponentDescriptor<NVTitleBarShadowNode>;
using NVToolbarComponentDescriptor = ConcreteComponentDescriptor<NVToolbarShadowNode>;

} // namespace react
} // namespace facebook
