
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "EventEmitters.h"
#include "Props.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char NVBottomAppBarComponentName[];

/*
 * `ShadowNode` for <NVBottomAppBar> component.
 */
using NVBottomAppBarShadowNode = ConcreteViewShadowNode<
    NVBottomAppBarComponentName,
    NVBottomAppBarProps,
NVBottomAppBarEventEmitter>;

JSI_EXPORT extern const char NVBottomSheetComponentName[];

/*
 * `ShadowNode` for <NVBottomSheet> component.
 */
using NVBottomSheetShadowNode = ConcreteViewShadowNode<
    NVBottomSheetComponentName,
    NVBottomSheetProps,
NVBottomSheetEventEmitter>;

JSI_EXPORT extern const char NVCollapsingBarComponentName[];

/*
 * `ShadowNode` for <NVCollapsingBar> component.
 */
using NVCollapsingBarShadowNode = ConcreteViewShadowNode<
    NVCollapsingBarComponentName,
    NVCollapsingBarProps>;

JSI_EXPORT extern const char NVCoordinatorLayoutComponentName[];

/*
 * `ShadowNode` for <NVCoordinatorLayout> component.
 */
using NVCoordinatorLayoutShadowNode = ConcreteViewShadowNode<
    NVCoordinatorLayoutComponentName,
    NVCoordinatorLayoutProps>;

JSI_EXPORT extern const char NVExtendedFloatingActionButtonComponentName[];

/*
 * `ShadowNode` for <NVExtendedFloatingActionButton> component.
 */
using NVExtendedFloatingActionButtonShadowNode = ConcreteViewShadowNode<
    NVExtendedFloatingActionButtonComponentName,
    NVExtendedFloatingActionButtonProps>;

JSI_EXPORT extern const char NVFloatingActionButtonComponentName[];

/*
 * `ShadowNode` for <NVFloatingActionButton> component.
 */
using NVFloatingActionButtonShadowNode = ConcreteViewShadowNode<
    NVFloatingActionButtonComponentName,
    NVFloatingActionButtonProps>;

JSI_EXPORT extern const char NVLeftBarComponentName[];

/*
 * `ShadowNode` for <NVLeftBar> component.
 */
using NVLeftBarShadowNode = ConcreteViewShadowNode<
    NVLeftBarComponentName,
    NVLeftBarProps>;

JSI_EXPORT extern const char NVNavigationBarComponentName[];

/*
 * `ShadowNode` for <NVNavigationBar> component.
 */
using NVNavigationBarShadowNode = ConcreteViewShadowNode<
    NVNavigationBarComponentName,
    NVNavigationBarProps>;

JSI_EXPORT extern const char NVNavigationStackComponentName[];

/*
 * `ShadowNode` for <NVNavigationStack> component.
 */
using NVNavigationStackShadowNode = ConcreteViewShadowNode<
    NVNavigationStackComponentName,
    NVNavigationStackProps,
NVNavigationStackEventEmitter>;

JSI_EXPORT extern const char NVRightBarComponentName[];

/*
 * `ShadowNode` for <NVRightBar> component.
 */
using NVRightBarShadowNode = ConcreteViewShadowNode<
    NVRightBarComponentName,
    NVRightBarProps>;

JSI_EXPORT extern const char NVSceneComponentName[];

/*
 * `ShadowNode` for <NVScene> component.
 */
using NVSceneShadowNode = ConcreteViewShadowNode<
    NVSceneComponentName,
    NVSceneProps,
NVSceneEventEmitter>;

JSI_EXPORT extern const char NVSegmentedTabComponentName[];

/*
 * `ShadowNode` for <NVSegmentedTab> component.
 */
using NVSegmentedTabShadowNode = ConcreteViewShadowNode<
    NVSegmentedTabComponentName,
    NVSegmentedTabProps>;

JSI_EXPORT extern const char NVSharedElementComponentName[];

/*
 * `ShadowNode` for <NVSharedElement> component.
 */
using NVSharedElementShadowNode = ConcreteViewShadowNode<
    NVSharedElementComponentName,
    NVSharedElementProps>;

JSI_EXPORT extern const char NVStatusBarComponentName[];

/*
 * `ShadowNode` for <NVStatusBar> component.
 */
using NVStatusBarShadowNode = ConcreteViewShadowNode<
    NVStatusBarComponentName,
    NVStatusBarProps>;

JSI_EXPORT extern const char NVTabBarComponentName[];

/*
 * `ShadowNode` for <NVTabBar> component.
 */
using NVTabBarShadowNode = ConcreteViewShadowNode<
    NVTabBarComponentName,
    NVTabBarProps,
NVTabBarEventEmitter>;

JSI_EXPORT extern const char NVTabBarPagerComponentName[];

/*
 * `ShadowNode` for <NVTabBarPager> component.
 */
using NVTabBarPagerShadowNode = ConcreteViewShadowNode<
    NVTabBarPagerComponentName,
    NVTabBarPagerProps,
NVTabBarPagerEventEmitter>;

JSI_EXPORT extern const char NVTabBarPagerRTLComponentName[];

/*
 * `ShadowNode` for <NVTabBarPagerRTL> component.
 */
using NVTabBarPagerRTLShadowNode = ConcreteViewShadowNode<
    NVTabBarPagerRTLComponentName,
    NVTabBarPagerRTLProps,
NVTabBarPagerRTLEventEmitter>;

JSI_EXPORT extern const char NVTabLayoutComponentName[];

/*
 * `ShadowNode` for <NVTabLayout> component.
 */
using NVTabLayoutShadowNode = ConcreteViewShadowNode<
    NVTabLayoutComponentName,
    NVTabLayoutProps>;

JSI_EXPORT extern const char NVTabLayoutRTLComponentName[];

/*
 * `ShadowNode` for <NVTabLayoutRTL> component.
 */
using NVTabLayoutRTLShadowNode = ConcreteViewShadowNode<
    NVTabLayoutRTLComponentName,
    NVTabLayoutRTLProps>;

JSI_EXPORT extern const char NVTabNavigationComponentName[];

/*
 * `ShadowNode` for <NVTabNavigation> component.
 */
using NVTabNavigationShadowNode = ConcreteViewShadowNode<
    NVTabNavigationComponentName,
    NVTabNavigationProps>;

JSI_EXPORT extern const char NVToolbarComponentName[];

/*
 * `ShadowNode` for <NVToolbar> component.
 */
using NVToolbarShadowNode = ConcreteViewShadowNode<
    NVToolbarComponentName,
    NVToolbarProps,
NVToolbarEventEmitter>;

} // namespace react
} // namespace facebook
