
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include <react/renderer/components/navigationreactnative/ShadowNodes.h>

namespace facebook {
namespace react {

extern const char NVBottomAppBarComponentName[] = "NVBottomAppBar";
extern const char NVBottomSheetComponentName[] = "NVBottomSheet";
extern const char NVCollapsingBarComponentName[] = "NVCollapsingBar";
extern const char NVCoordinatorLayoutComponentName[] = "NVCoordinatorLayout";
extern const char NVExtendedFloatingActionButtonComponentName[] = "NVExtendedFloatingActionButton";
extern const char NVFloatingActionButtonComponentName[] = "NVFloatingActionButton";
extern const char NVLeftBarComponentName[] = "NVLeftBar";
extern const char NVNavigationBarComponentName[] = "NVNavigationBar";
extern const char NVNavigationStackComponentName[] = "NVNavigationStack";
extern const char NVRightBarComponentName[] = "NVRightBar";
extern const char NVSceneComponentName[] = "NVScene";
extern const char NVSegmentedTabComponentName[] = "NVSegmentedTab";
extern const char NVSharedElementComponentName[] = "NVSharedElement";
extern const char NVStatusBarComponentName[] = "NVStatusBar";
extern const char NVTabBarComponentName[] = "NVTabBar";
extern const char NVTabBarPagerComponentName[] = "NVTabBarPager";
extern const char NVTabBarPagerRTLComponentName[] = "NVTabBarPagerRTL";
extern const char NVTabLayoutComponentName[] = "NVTabLayout";
extern const char NVTabLayoutRTLComponentName[] = "NVTabLayoutRTL";
extern const char NVTabNavigationComponentName[] = "NVTabNavigation";
extern const char NVToolbarComponentName[] = "NVToolbar";

} // namespace react
} // namespace facebook
