
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "navigationreactnative.h"

namespace facebook {
namespace react {

static facebook::jsi::Value __hostFunction_NativeMaterial3ModuleSpecJSI_getConstants(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, ObjectKind, "getConstants", "()Ljava/util/Map;", args, count, cachedMethodId);
}

NativeMaterial3ModuleSpecJSI::NativeMaterial3ModuleSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["getConstants"] = MethodMetadata {0, __hostFunction_NativeMaterial3ModuleSpecJSI_getConstants};
}

std::shared_ptr<TurboModule> navigationreactnative_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "Material3") {
    return std::make_shared<NativeMaterial3ModuleSpecJSI>(params);
  }
  return nullptr;
}

} // namespace react
} // namespace facebook
