
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniH.js
 */

#pragma once

#include <ReactCommon/JavaTurboModule.h>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>
#include <react/renderer/components/navigationreactnative/NVActionBarComponentDescriptor.h>
#include <react/renderer/components/navigationreactnative/NVBarButtonComponentDescriptor.h>
#include <react/renderer/components/navigationreactnative/NVBottomSheetComponentDescriptor.h>
#include <react/renderer/components/navigationreactnative/NVNavigationBarComponentDescriptor.h>
#include <react/renderer/components/navigationreactnative/NVSearchBarComponentDescriptor.h>
#include <react/renderer/components/navigationreactnative/NVTabBarItemComponentDescriptor.h>
#include <react/renderer/components/navigationreactnative/NVTitleBarComponentDescriptor.h>

namespace facebook {
namespace react {

/**
 * JNI C++ class for module 'NativeMaterial3Module'
 */
class JSI_EXPORT NativeMaterial3ModuleSpecJSI : public JavaTurboModule {
public:
  NativeMaterial3ModuleSpecJSI(const JavaTurboModule::InitParams &params);
};


JSI_EXPORT
std::shared_ptr<TurboModule> navigationreactnative_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params);

} // namespace react
} // namespace facebook
